apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: security
type: Opaque
data:
  admin-user: YWRtaW4=  # base64 of 'admin'
  admin-password: cGFzc3dvcmQ=  # base64 of 'password'
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: security
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 of 'postgres'
  password: cGFzc3dvcmQ=  # base64 of 'password'