server:
  port: 8081
#logging:
#  level:
#    org.springframework.beans: DEBUG
#    org.springframework.context.annotation: DEBUG
#    org.springframework.jdbc.datasource.init: DEBUG

spring:

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fin_arch
    username: fin_user
    password: fin_pass
    initialization-mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7070/.well-known/jwks.json
