services:
  #  coredns:
  #    image: coredns/coredns:1.11.1
  #    profiles: [ "full", "demo" ]
  #    command: -conf /Corefile
  #    volumes:
  #      - ../01-networking/coredns/Corefile:/Corefile:ro
  #
  #    network_mode: host

  traefik:
    image: traefik:v3.6.5
    profiles: [ "full", "demo" ]
    #    user: "0:0"
    #    group_add:
    #      - "988"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.fin.soul.test`)"
      - "traefik.http.routers.traefik.service=api@internal"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

      - "--api.dashboard=true"
      - "--api.insecure=true"

    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard

    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock
      #- /home/gui.linux/.lima/docker/sock/docker.sock:/var/run/docker.sock:ro

    networks:
      - platform
