apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-kubernetes
  namespace: security
data:
  config.hcl: |
    path "auth/kubernetes" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    kubernetes_host = "https://kubernetes.default.svc"