auth:
  enabled: ${AUTH_ENABLED:true}

server:
  port: 8080

spring:
  application:
    name: account-service

  cloud:
    function:
      definition: producer;consumer;processor
    stream:
      bindings:
        consumer-in-0:
          destination: output-topic
          group: consumer-group
        processor-in-0:
          destination: input-topic
          group: processor-group
        processor-out-0:
          destination: output-topic
        producer-out-0:
          destination: input-topic

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security.oauth2: DEBUG

kafka:
  enabled: false