apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus
  namespace: apps
spec:
  podSelector: { }
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              scope: observability
